name: travel_kz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  shared_preferences: ^2.5.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

